root: true
ignorePatterns:
  - '*.config.js'
  - '*.d.ts'
env:
  browser: true # Enables browser globals like window and document
  es2021: true
  node: true # Enables Node.js global variables and Node.js scoping.
  amd: true # Enables require() and define() as global variables as per the amd spec.
extends:
  - eslint:recommended
  - airbnb
  - airbnb/hooks
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript # important bit for when using typescript
  - next
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true # Enable JSX since we're using React
  ecmaVersion: 2020 # Use the latest ecmascript standard
  sourceType: module # Allows using import/export statements
plugins:
  - import
  - react
  - '@typescript-eslint' # important bit for when using typescript
settings:
  react:
    version: detect # Automatically detect the react version
rules:
  no-console: 1
  no-plusplus:
    - 2
    - { allowForLoopAfterthoughts: true }
  no-underscore-dangle:
    - 1
    - { allow: ['_id'] }
  # no-param-reassign: 0
  no-nested-ternary: 0
  no-use-before-define: 0
  import/extensions:
    - 1
    - { json: always }
  import/prefer-default-export: 0
  jsx-a11y/anchor-is-valid:
    - 1
    - {
        components: ['Link'],
        specialLink: ['passHref', 'hrefLeft', 'hrefRight'],
        aspects: ['invalidHref', 'preferButton'],
      }
  jsx-a11y/label-has-associated-control:
    - 2
    - { controlComponents: ['Dropdown'] }
  jsx-a11y/click-events-have-key-events: 0
  react/jsx-props-no-spreading: 0
  react/jsx-filename-extension: 0
  react/prop-types: 0
